# Generated by Django 5.2.6 on 2025-09-30 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('ID_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('ID_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_madera',
            fields=[
                ('ID_tipo_madera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='camion',
            fields=[
                ('ID_camion', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='carga',
            fields=[
                ('ID_carga', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('tipo_madera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo_madera')),
            ],
        ),
    ]
