# Generated by Django 5.2.7 on 2025-10-16 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_especialidad_medicamento_paciente_ubicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_cita', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='AGENDADA', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['-fecha_hora_cita'],
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('tipo_registro', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('medicamentos_asociados', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Historiales Clínicos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_consulta_minutos', models.IntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aseguradora', models.CharField(max_length=100)),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('tipo_cobertura', models.CharField(choices=[('BASICA', 'Cobertura Básica'), ('INTERMEDIA', 'Cobertura Intermedia'), ('COMPLETA', 'Cobertura Completa'), ('PREMIUM', 'Cobertura Premium')], default='BASICA', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('porcentaje_cobertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Seguros',
            },
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='categoria',
            field=models.CharField(choices=[('ANALGESICO', 'Analgésico'), ('ANTIBIOTICO', 'Antibiótico'), ('ANTIINFLAMATORIO', 'Antiinflamatorio'), ('ANTIHIPERTENSIVO', 'Antihipertensivo'), ('VITAMINA', 'Vitamina/Suplemento'), ('ANTIHISTAMINICO', 'Antihistamínico'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='medico',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('NE', 'Prefiero no especificar')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('NE', 'Prefiero no especificar')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='via_administracion',
            field=models.CharField(choices=[('ORAL', 'Vía Oral'), ('TOPICA', 'Vía Tópica'), ('INTRAVENOSA', 'Vía Intravenosa'), ('INTRAMUSCULAR', 'Vía Intramuscular'), ('SUBCUTANEA', 'Vía Subcutánea'), ('SUBLINGUAL', 'Vía Sublingual'), ('INHALATORIA', 'Vía Inhalatoria')], default='ORAL', max_length=15),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='consulta_realizada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_origen', to='api.consultamedica'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='api.medico'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='api.paciente'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='api.paciente'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_clinicos', to='api.medico'),
        ),
        migrations.AddField(
            model_name='horario',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.medico'),
        ),
        migrations.AddField(
            model_name='seguro',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='api.paciente'),
        ),
    ]
